# Site settings
email: ps@outlook.in
baseurl: ""
paginate: 15
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: pratik sheth
description: Somewhat dexterous data engineer with range of skills
url: https://daftengineer.github.io
twitter_username: daftengineer
default_img: 

# Profile settings
name: Pratik Sheth
profile_img: 
profile: 
social:
  github: https://github.com/daftengineer
  twitter: https://twitter.com/daftengineer

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
